In [1]:
import os
os.getcwd()

'/Users/ethandominic/Ethan-Dominic-AIPI-561-Repo/week4/scripts'

In [2]:
import pandas as pd
import numpy as np
from scipy.stats import ks_2samp

baseline = pd.read_parquet("../data/demand_enriched_baseline.parquet")
baseline.head()

,PULocationID,time_bucket,trip_count,hour,minute,dayofweek,is_weekend,month,dayofyear,weekofyear,...,is_airport_zone,zone_slot_baseline,lag_15min,lag_1h,lag_2h,lag_1day,lag_1week,roll_mean_1h,roll_mean_2h,roll_mean_1day
0,4,2026-01-01 00:00:00,9,0,0,3,0,1,1,1,...,0,0.927273,0.0,3.0,2.0,1.0,1.0,3.00,2.625,0.916667
1,4,2026-01-01 00:15:00,7,0,15,3,0,1,1,1,...,0,0.903030,9.0,5.0,3.0,4.0,1.0,4.50,3.500,1.000000
2,4,2026-01-01 00:30:00,3,0,30,3,0,1,1,1,...,0,0.872727,7.0,4.0,1.0,1.0,0.0,5.00,4.000,1.031250
3,4,2026-01-01 00:45:00,8,0,45,3,0,1,1,1,...,0,0.945455,3.0,0.0,3.0,1.0,0.0,4.75,4.250,1.052083
4,4,2026-01-01 01:00:00,7,1,0,3,0,1,1,1,...,0,0.939394,8.0,9.0,3.0,2.0,1.0,6.75,4.875,1.125000

In [3]:
print(baseline["time_bucket"].min())
print(baseline["time_bucket"].max())

2026-01-01 00:00:00
2026-01-15 23:45:00

In [4]:
new_data = pd.read_parquet("../data/demand_enriched_week4.parquet")
new_data.head()

,PULocationID,time_bucket,trip_count,hour,minute,dayofweek,is_weekend,month,dayofyear,weekofyear,...,is_airport_zone,zone_slot_baseline,lag_15min,lag_1h,lag_2h,lag_1day,lag_1week,roll_mean_1h,roll_mean_2h,roll_mean_1day
0,4,2023-01-01 00:00:00,1,0,0,6,1,1,1,52,...,0,7.721212,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,4,2023-01-01 00:15:00,4,0,15,6,1,1,1,52,...,0,8.551515,1.0,NaN,NaN,NaN,NaN,1.0,1.0,1.0
2,4,2023-01-01 00:30:00,4,0,30,6,1,1,1,52,...,0,9.236364,4.0,NaN,NaN,NaN,NaN,2.5,2.5,2.5
3,4,2023-01-01 00:45:00,5,0,45,6,1,1,1,52,...,0,10.581818,4.0,NaN,NaN,NaN,NaN,3.0,3.0,3.0
4,4,2023-01-01 01:00:00,4,1,0,6,1,1,1,52,...,0,11.975758,5.0,1.0,NaN,NaN,NaN,3.5,3.5,3.5

In [5]:
print(new_data["time_bucket"].min())
print(new_data["time_bucket"].max())

2023-01-01 00:00:00
2026-02-28 23:45:00

In [6]:
print(new_data.shape)
arr_1 = new_data["trip_count"].values[:2]
arr_2 = np.array([1, 2])
print(arr_1)
print(arr_2)
print(arr_1 == arr_2)
print((arr_1 == arr_2).sum())
print(2 == (arr_1 == arr_2).sum())

(6320160, 32)
[1 4]
[1 2]
[ True False]
1
False

In [10]:
print(baseline["time_bucket"].min())
print(baseline["time_bucket"].max())
new_cutoff = pd.Timestamp("2026-02-02")
feb_data = new_data[new_data["time_bucket"] >= new_cutoff]
print(feb_data["time_bucket"].min())
print(feb_data["time_bucket"].max())
ks_2_test_results = ks_2samp(baseline["trip_count"], feb_data["trip_count"])
print(ks_2_test_results)
print(ks_2_test_results.statistic)
print(ks_2_test_results.pvalue)

2026-01-01 00:00:00
2026-01-15 23:45:00
2026-02-02 00:00:00
2026-02-28 23:45:00
KstestResult(statistic=0.04248565085553391, pvalue=3.3709986942707705e-83, statistic_location=0, statistic_sign=-1)
0.04248565085553391
3.3709986942707705e-83

In [12]:
import evidently

api-reference/generate.py --local-source-code

NameError: name 'api' is not defined